package by.assxmblxr.marketplace.dao;

import by.assxmblxr.marketplace.model.Order;
import by.assxmblxr.marketplace.model.OrderStatus;

import java.util.List;
import java.util.Optional;

/**
 * Data access interface for {@link Order} entities.
 */
public interface OrderDao {

  /**
   * Persists a new order. The {@code id} and {@code createdAt} of the given order are ignored;
   * both are generated by the database and returned in the result.
   *
   * @param order the order to create; {@code id}/{@code createdAt} may be {@code null}
   * @return the persisted order, with the database-generated {@code id} and {@code createdAt} set
   */
  Order save(Order order);

  /**
   * Updates the status of an existing order.
   *
   * @param id          the id of the order to update
   * @param orderStatus the new status to set
   * @return {@code true} if an order with the given id was found and updated, {@code false} otherwise
   */
  boolean updateStatus(Long id, OrderStatus orderStatus);

  /**
   * Finds an order by its primary key.
   *
   * @param id the order id to look up
   * @return an {@link Optional} containing the matching order,
   *         or {@link Optional#empty()} if no order with the given id exists
   */
  Optional<Order> findById(Long id);

  /**
   * Returns a page of orders placed by a given buyer, most recent first.
   *
   * @param buyerId  the id of the buyer whose orders to return
   * @param page     the 1-based page number
   * @param pageSize the maximum number of orders per page
   * @return the requested page of orders, ordered by {@code createdAt} descending;
   *         an empty list if the buyer has no orders or the page is out of range
   */
  List<Order> findAllByBuyer(Long buyerId, int page, int pageSize);
}