package by.assxmblxr.marketplace.dao;

import by.assxmblxr.marketplace.model.OrderItem;
import by.assxmblxr.marketplace.model.OrderItemStatus;

import java.util.List;
import java.util.Optional;

/**
 * Data access interface for {@link OrderItem} entities.
 */
public interface OrderItemDao {

  /**
   * Persists a new order line item. The {@code id} of the given item is ignored;
   * it is generated by the database and returned in the result.
   *
   * @param orderItem the order item to create; {@code id} may be {@code null}
   * @return the persisted order item, with the database-generated {@code id} set
   */
  OrderItem save(OrderItem orderItem);

  /**
   * Updates the status of an existing order line item.
   *
   * @param id              the id of the order item to update
   * @param orderItemStatus the new status to set
   * @return {@code true} if an order item with the given id was found and updated,
   *         {@code false} otherwise
   */
  boolean updateStatus(Long id, OrderItemStatus orderItemStatus);

  /**
   * Finds an order item by its primary key.
   *
   * @param id the order item id to look up
   * @return an {@link Optional} containing the matching order item,
   *         or {@link Optional#empty()} if no order item with the given id exists
   */
  Optional<OrderItem> findById(Long id);

  /**
   * Returns every line item belonging to a given order.
   *
   * @param orderId the id of the order whose items to return
   * @return the order's line items, ordered by id; an empty list if the order has none
   */
  List<OrderItem> findAllByOrder(Long orderId);

  /**
   * Returns a page of order line items across all orders for products sold by a given seller.
   *
   * @param sellerId the id of the seller whose sold items to return
   * @param page     the 1-based page number
   * @param pageSize the maximum number of items per page
   * @return the requested page of order items, ordered by id;
   *         an empty list if the seller has no matching items or the page is out of range
   */
  List<OrderItem> findAllBySeller(Long sellerId, int page, int pageSize);
}