package by.assxmblxr.marketplace.dao;

import by.assxmblxr.marketplace.model.ProductImage;

import java.util.List;
import java.util.Map;
import java.util.Optional;

/**
 * Data access interface for {@link ProductImage} entities.
 * <p>
 * Only DB access belongs here; deleting the underlying uploaded file (via {@code FileStorage})
 * is orchestrated by the service layer, not this DAO.
 */
public interface ProductImageDao {

  /**
   * Persists a new product image record. The {@code id} of the given image is ignored;
   * it is generated by the database and returned in the result.
   *
   * @param productImage the image to create; {@code id} may be {@code null}
   * @return the persisted image, with the database-generated {@code id} set
   */
  ProductImage save(ProductImage productImage);

  /**
   * Updates an existing image's storage path and display order.
   *
   * @param productImage the image data to write, identified by {@link ProductImage#id()}
   * @return an {@link Optional} containing the updated image if an image with the
   *         given id was found, or {@link Optional#empty()} otherwise
   */
  Optional<ProductImage> update(ProductImage productImage);

  /**
   * Deletes an image record by id. Does not touch the underlying stored file.
   *
   * @param id the id of the image to delete
   * @return {@code true} if an image with the given id was found and deleted, {@code false} otherwise
   */
  boolean delete(Long id);

  /**
   * Finds an image by its primary key.
   *
   * @param id the image id to look up
   * @return an {@link Optional} containing the matching image,
   *         or {@link Optional#empty()} if no image with the given id exists
   */
  Optional<ProductImage> findById(Long id);

  /**
   * Finds the main (first-displayed) photo of a product, i.e. the image with {@code order == 1}.
   *
   * @param productId the id of the product whose main photo to find
   * @return an {@link Optional} containing the main photo,
   *         or {@link Optional#empty()} if the product has no images
   */
  Optional<ProductImage> findMainPhoto(Long productId);

  /**
   * Returns every image belonging to a given product.
   *
   * @param productId the id of the product whose images to return
   * @return the product's images, ordered by display position; an empty list if it has none
   */
  List<ProductImage> findAllByProductId(Long productId);

  /**
   * Batch-resolves the main photo for multiple products at once, avoiding an N+1 query
   * when rendering a list of products (e.g. a catalog page).
   *
   * @param productIds the ids of the products to look up main photos for
   * @return a map from product id to its main photo; products with no images are omitted
   */
  Map<Long, ProductImage> findAllMainPhotos(List<Long> productIds);
}