package by.assxmblxr.marketplace.dao;

import by.assxmblxr.marketplace.model.Product;

import java.math.BigDecimal;
import java.util.List;
import java.util.Optional;

/**
 * Data access interface for {@link Product} entities.
 */
public interface ProductDao {

  /**
   * Persists a new product listing. The {@code id}, {@code isDeleted}, and {@code rating}
   * of the given product are ignored; {@code id} is generated by the database,
   * {@code isDeleted} defaults to {@code false}, and {@code rating} starts as {@code null}.
   *
   * @param product the product to create
   * @return the persisted product, with the database-generated {@code id} set
   */
  Product save(Product product);

  /**
   * Updates an existing product's category, name, description, price, and stock count.
   *
   * @param product the product data to write, identified by {@link Product#id()}
   * @return an {@link Optional} containing the updated product if a product with the
   *         given id was found, or {@link Optional#empty()} otherwise
   */
  Optional<Product> update(Product product);

  /**
   * Deactivates a product listing, hiding it from active listings without deleting its row.
   *
   * @param id the id of the product to deactivate
   * @return {@code true} if an active product with the given id was found and deactivated;
   *         {@code false} if no such product exists or it was already deactivated
   */
  boolean deactivate(Long id);

  /**
   * Finds a product by its primary key, regardless of its active/deactivated state.
   *
   * @param id the product id to look up
   * @return an {@link Optional} containing the matching product,
   *         or {@link Optional#empty()} if no product with the given id exists
   */
  Optional<Product> findById(Long id);

  /**
   * Returns a page of active (non-deactivated) products, highest rated first.
   *
   * @param page     the 1-based page number
   * @param pageSize the maximum number of products per page
   * @return the requested page of active products, ordered by rating descending
   *         (unrated products last); an empty list if the page is out of range
   */
  List<Product> findAllActive(int page, int pageSize);

  /**
   * Returns a page of products listed by a given seller.
   *
   * @param sellerId the id of the seller whose products to return
   * @param page     the 1-based page number
   * @param pageSize the maximum number of products per page
   * @return the requested page of products, ordered by id;
   *         an empty list if the seller has no products or the page is out of range
   */
  List<Product> findAllBySeller(Long sellerId, int page, int pageSize);

  /**
   * Returns a page of products belonging to a given category, highest rated first.
   *
   * @param categoryId the id of the category to filter by
   * @param page       the 1-based page number
   * @param pageSize   the maximum number of products per page
   * @return the requested page of products, ordered by rating descending
   *         (unrated products last); an empty list if the category has no products
   *         or the page is out of range
   */
  List<Product> findAllByCategory(Long categoryId, int page, int pageSize);

  /**
   * Overwrites a product's cached average rating, typically after a review is
   * added, edited, or removed.
   *
   * @param productId the id of the product to update
   * @param rating    the new rating value to store
   */
  void updateRating(Long productId, BigDecimal rating);
}