package by.assxmblxr.marketplace.dao;

import by.assxmblxr.marketplace.model.RememberToken;

import java.time.OffsetDateTime;
import java.util.Optional;

/**
 * Data access interface for {@link RememberToken} entities.
 */
public interface RememberTokenDao {

  /**
   * Persists a new remember-me token. {@link RememberToken#tokenHash()} is the primary
   * key and must already be set by the caller (unlike other entities' surrogate ids,
   * it is not generated by the database).
   *
   * @param token the token to create
   * @return the persisted token, unchanged
   */
  RememberToken save(RememberToken token);

  /**
   * Finds a token by its hash. Used to authenticate a device from a remember-me cookie.
   *
   * @param tokenHash the hash of the raw token presented by the client
   * @return an {@link Optional} containing the matching token,
   *         or {@link Optional#empty()} if no token with the given hash exists
   */
  Optional<RememberToken> findByTokenHash(String tokenHash);

  /**
   * Updates a token's expiration, implementing sliding expiration: a device that keeps
   * using its token stays logged in without ever needing to log in again.
   *
   * @param tokenHash    the hash of the token to extend
   * @param newExpiresAt the new expiration time to set
   * @return {@code true} if a token with the given hash was found and updated, {@code false} otherwise
   */
  boolean extendExpiration(String tokenHash, OffsetDateTime newExpiresAt);

  /**
   * Deletes a single token by its hash. Used to log out one device.
   *
   * @param tokenHash the hash of the token to delete
   * @return {@code true} if a token with the given hash was found and deleted, {@code false} otherwise
   */
  boolean deleteByTokenHash(String tokenHash);

  /**
   * Deletes all tokens belonging to a user. Used to log out every device at once
   * (e.g. on password change).
   *
   * @param userId the id of the user whose tokens should be deleted
   * @return the number of tokens deleted
   */
  int deleteAllByUserId(Long userId);
}