package by.assxmblxr.marketplace.dao;

import by.assxmblxr.marketplace.model.Review;

import java.math.BigDecimal;
import java.util.List;
import java.util.Optional;

/**
 * Data access interface for {@link Review} entities.
 */
public interface ReviewDao {

  /**
   * Persists a new review. The {@code id} and {@code createdAt} of the given review are
   * ignored; both are generated by the database and returned in the result.
   *
   * @param review the review to create; {@code id}/{@code createdAt} may be {@code null}
   * @return the persisted review, with the database-generated {@code id} and {@code createdAt} set
   */
  Review save(Review review);

  /**
   * Updates an existing review's rating and description.
   *
   * @param review the review data to write, identified by {@link Review#id()}
   * @return an {@link Optional} containing the updated review if a review with the
   *         given id was found, or {@link Optional#empty()} otherwise
   */
  Optional<Review> update(Review review);

  /**
   * Deletes a review by id.
   *
   * @param id the id of the review to delete
   * @return {@code true} if a review with the given id was found and deleted, {@code false} otherwise
   */
  boolean delete(Long id);

  /**
   * Returns every review written by a given user, most recent first.
   *
   * @param userId the id of the user whose reviews to return
   * @return the user's reviews, ordered by {@code createdAt} descending; an empty list if none exist
   */
  List<Review> findAllByUser(Long userId);

  /**
   * Returns a page of reviews for a given product, highest rated first.
   *
   * @param productId the id of the product whose reviews to return
   * @param page      the 1-based page number
   * @param pageSize  the maximum number of reviews per page
   * @return the requested page of reviews, ordered by rating descending;
   *         an empty list if the product has no reviews or the page is out of range
   */
  List<Review> findAllByProduct(Long productId, int page, int pageSize);

  /**
   * Computes the average rating across all reviews for a product.
   *
   * @param productId the id of the product to average ratings for
   * @return an {@link Optional} containing the average rating,
   *         or {@link Optional#empty()} if the product has no reviews
   */
  Optional<BigDecimal> calculateAverageRating(Long productId);
}